spring:
  application:
    name: report-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
report-service:
  hibernate:
    show-sql: true
    format-sql: false	
    generate-statistics: false
    use-identifier-rollback: true
    statement-cache:
      size: 0
    connection:
      autocommit: false
      isolation: 2
      pool-size: 0
    jdbc:
      batch-size: 8
      fetch-size: 50
      use-streams-for-binary: true